"""
Friendly one-time setup wizard.

Run:  python setup.py

It does three things:
  1. Asks for your API keys and writes them to a `.env` file.
  2. Finds your CV (a PDF in inputs/, or pasted text in inputs/PUT_YOUR_CV_HERE.txt)
     and extracts the text.
  3. Asks a few career questions (or reads inputs/QUESTIONNAIRE.md if you filled it
     in) and writes everything to inputs/profile.json.

After this finishes, run:  python main.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent
INPUTS = ROOT / "inputs"
PROFILE_PATH = INPUTS / "profile.json"
ENV_PATH = ROOT / ".env"
CV_TXT = INPUTS / "PUT_YOUR_CV_HERE.txt"

BAR = "─" * 62


def banner(text: str) -> None:
    print(f"\n{BAR}\n  {text}\n{BAR}")


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


def ask_lines(prompt: str) -> list[str]:
    print(f"{prompt}\n  (one per line; press Enter on a blank line when done)")
    out = []
    while True:
        line = input("  • ").strip()
        if not line:
            break
        out.append(line)
    return out


# ── 1. API keys ─────────────────────────────────────────────────────────────

def collect_keys() -> dict:
    banner("STEP 1 of 3  ·  API keys")
    print("These let the app talk to the AI and (optionally) your Notion dashboard.")
    print("Free sign-ups:  Groq → console.groq.com   ·   Notion → notion.so/my-integrations\n")

    keys = {}
    keys["GROQ_API_KEY"] = ask("Groq API key (required)")
    keys["GEMINI_API_KEY"] = ask("Gemini API key (optional, press Enter to skip)")
    keys["NOTION_API_KEY"] = ask("Notion API key (optional, press Enter to skip)")
    keys["NOTION_DATABASE_ID"] = ask("Notion database ID (optional)")
    return keys


def write_env(keys: dict) -> None:
    lines = [
        "# Generated by setup.py — keep this file private, never share it.",
        f"GROQ_API_KEY={keys['GROQ_API_KEY']}",
        f"GEMINI_API_KEY={keys['GEMINI_API_KEY']}",
        f"NOTION_API_KEY={keys['NOTION_API_KEY']}",
        f"NOTION_DATABASE_ID={keys['NOTION_DATABASE_ID']}",
        "",
        "# Tuning (sensible defaults — change if you like)",
        "MIN_MATCH_SCORE=7",
        "SCRAPE_DELAY_SECONDS=2",
        "MAX_JOBS_PER_BOARD=15",
    ]
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n  ✓ Saved your keys to {ENV_PATH.name}")


# ── 2. CV text ────────────────────────────────────────────────────────────────

def find_cv_text() -> str:
    # Prefer a real PDF dropped into inputs/
    pdfs = sorted(INPUTS.glob("*.pdf"))
    if pdfs:
        try:
            from pypdf import PdfReader
            reader = PdfReader(str(pdfs[0]))
            text = "\n".join((page.extract_text() or "") for page in reader.pages).strip()
            if text:
                print(f"  ✓ Read CV from {pdfs[0].name} ({len(text)} characters)")
                return text
        except Exception as exc:
            print(f"  ! Could not read {pdfs[0].name}: {exc}")

    # Fall back to pasted text
    if CV_TXT.exists():
        text = CV_TXT.read_text(encoding="utf-8").strip()
        if text and "HOW TO ADD YOUR CV" not in text:
            print(f"  ✓ Read CV from {CV_TXT.name}")
            return text

    print("  ! No CV found. Drop a PDF in inputs/ or paste text into PUT_YOUR_CV_HERE.txt.")
    return ""


# ── 3. Career profile ─────────────────────────────────────────────────────────

def collect_profile(cv_text: str) -> dict:
    banner("STEP 3 of 3  ·  About you & the jobs you want")
    print("Answer these so the app knows what to search for and how to position you.\n")

    name = ask("Your full name (as it should appear on your CV)")
    headline = ask("Professional headline (one line)")
    location = ask("Location (city, country)")
    phone = ask("Phone (optional)")
    email = ask("Email")
    linkedin = ask("LinkedIn URL (optional)")

    print()
    queries = ask_lines("Job titles to search for")
    print()
    locations = ask_lines("Locations / regions to search (e.g. Europe, Remote, London)")

    print("\nIn a few sentences: what are you optimising for in your career?")
    print("(industries, company type, scope, growth, dream-fit vs. hard-no)")
    vision = input("→ ").strip()

    return {
        "name": name,
        "headline": headline,
        "contact": {"location": location, "phone": phone, "email": email, "linkedin": linkedin},
        "cv_text": cv_text,
        "career_vision": vision,
        "search_queries": queries,
        "search_locations": locations or ["Europe"],
    }


# ── Main ────────────────────────────────────────────────────────────────────

def main() -> None:
    banner("Job Hunter — Setup Wizard")
    print("This takes about 3 minutes. You can re-run it anytime to change things.")

    keys = collect_keys()
    write_env(keys)

    banner("STEP 2 of 3  ·  Your CV")
    cv_text = find_cv_text()

    profile = collect_profile(cv_text)
    INPUTS.mkdir(exist_ok=True)
    PROFILE_PATH.write_text(json.dumps(profile, indent=2, ensure_ascii=False), encoding="utf-8")

    banner("All done! 🎉")
    print(f"  ✓ Profile saved to {PROFILE_PATH.relative_to(ROOT)}")
    print("\n  Next step — run your first job hunt:\n")
    print("      python main.py\n")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\n\nSetup cancelled. Run `python setup.py` again whenever you're ready.")
        sys.exit(1)
